spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://localhost:3306/retail?useSSL=false # localhost:puerto/DBNAME?useSSL=false / no usamos SSL
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    maximum-pool-size: 10
    minimum-idle: 3
    idle-timeout: 30000
    connection-timeout: 20000
    max-lifetime: 1800000
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      cache:
        enabled: true
        ttl: 35s
        capacity: 256
      health-check:
        enabled: true
        interval: 25s

# OpenAPI/Swagger Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


logging:
  level:
    com.mitocode.customer_service.client: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    org.springframework.cloud.openfeign: DEBUG